name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SHORT_SHA: ''
      BRANCH: ''
      TAG: ''
      DOCKERHUB_REPOSITORY: stonemoe/anypush

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set tag
        if: contains(github.ref, 'refs/tags/')
        run: echo ::set-env name=TAG::${GITHUB_REF/refs\/tags\//}
      - name: Set branch
        if: contains(github.ref, 'refs/heads/')
        run: echo ::set-env name=BRANCH::${GITHUB_REF/refs\/heads\//}
      - name: Set SHA
        run: echo ::set-env name=SHORT_SHA::$(echo ${GITHUB_SHA} | cut -c1-8)

      - name: Docker login
        run: echo ${DOCKERHUB_PASSWORD} | docker login --username ${DOCKERHUB_USERNAME} --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker build
        run: docker build . --file Dockerfile --tag ${DOCKERHUB_REPOSITORY}:rolling-${BRANCH}-${SHORT_SHA}

      - name: Docker push rolling image
        if: env.BRANCH != ''
        run: docker push ${DOCKERHUB_REPOSITORY}:rolling-${BRANCH}-${SHORT_SHA}

      - name: Docker push stable image
        if: env.TAG != ''
        run: docker tag ${DOCKERHUB_REPOSITORY}:rolling-${BRANCH}-${SHORT_SHA} ${DOCKERHUB_REPOSITORY}:${TAG} && docker push ${DOCKERHUB_REPOSITORY}:${TAG}

      - name: Sync Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Create Release
        if: env.TAG != ''
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          body: |
            ```
            docker run --name=anypush --restart=unless-stopped -e WEBHOOK_URL=https://example.com/api -p 0.0.0.0:587:587 ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.TAG }}
            ```
          draft: false
          prerelease: false
