name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SHORT_SHA: ''
      TAG: ''
      DOCKERHUB_REPOSITORY: stonemoe/anypush

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set tag
        id: get_tag
        run: echo ::set-env name=TAG::${GITHUB_REF/refs\/tags\//}
      - name: Set SHA
        id: get_sha
        run: echo ::set-env name=SHORT_SHA::$(echo ${GITHUB_SHA} | cut -c1-8)

      - name: Docker login
        run: echo '${DOCKERHUB_PASSWORD}' | docker login --username ${DOCKERHUB_USERNAME} --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker build
        run: docker build . --file Dockerfile --tag ${DOCKERHUB_REPOSITORY}:rolling-${SHORT_SHA}

      - name: Docker push rolling image
        run: docker push ${DOCKERHUB_REPOSITORY}:rolling-${SHORT_SHA}

      - name: Docker push stable image
        if: ${{ SHORT_SHA }} != ''
        run: docker tag ${DOCKERHUB_REPOSITORY}:rolling-${SHORT_SHA} ${DOCKERHUB_REPOSITORY}:${TAG} && docker push ${DOCKERHUB_REPOSITORY}:${TAG}

      - name: Sync Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
